### ISSUE TITLE
error after keying "telegramCredentials" on start.py

### ISSUE THREAD

**Issue by idevonic** [C-Nigel/BBDC-2BPracticalSlotAlertBot#1]
Upon using start.py I got this error after keying "telegramCredentials" but "loginCredentials" is ok.

```
File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main\telegramBot.py", line 8, in <module>
    import BLL
  File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main\BLL.py", line 11, in <module>
    import telegramBot
  File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main\telegramBot.py", line 63, in <module>
    thread = threading.Thread(target=initlization.generateJSON())
  File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main\initlization.py", line 43, in generateJSON
    chatID = telegramBot.getChatId(botID)
  File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main\telegramBot.py", line 44, in getChatId
    BLL.printMessage(
AttributeError: partially initialized module 'BLL' has no attribute 'printMessage' (most likely due to a circular import)
```

**Comment by Nigel-Cheong** [comment]
Hi, thanks for pointing it out. I just pushed a update to fix this issue. Do try again and let me know if the issue has been resolved on your end.

**Comment by idevonic** [comment]
> Hi, thanks for pointing it out. I just pushed a update to fix this issue. Do try again and let me know if the issue has been resolved on your end.

Hello, thanks for your response again.

Everything works except for the telegram portion. 
After entering `Enter your telegram bot ID` which I entered my bot API token.
`[06/09/2021 02:33:42] Attempting to connect to your device..
[06/09/2021 02:33:44] Device successfully connected`
However, there was no response from using `/start` from my bot.

Tried to investigate telegramBot.py which gave me:
```
C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main (1)\BBDC-2BPracticalSlotAlertBot-main>python telegramBot.py
Traceback (most recent call last):
  File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main (1)\BBDC-2BPracticalSlotAlertBot-main\telegramBot.py", line 9, in <module>
    import initlization
  File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main (1)\BBDC-2BPracticalSlotAlertBot-main\initlization.py", line 6, in <module>
    import telegramBot
  File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main (1)\BBDC-2BPracticalSlotAlertBot-main\telegramBot.py", line 64, in <module>
    thread = threading.Thread(target=initlization.generateJSON())
AttributeError: partially initialized module 'initlization' has no attribute 'generateJSON' (most likely due to a circular import)

C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main (1)\BBDC-2BPracticalSlotAlertBot-main>
```

**Comment by Nigel-Cheong** [comment]
```
C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main (1)\BBDC-2BPracticalSlotAlertBot-main>python telegramBot.py
Traceback (most recent call last):
  File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main (1)\BBDC-2BPracticalSlotAlertBot-main\telegramBot.py", line 9, in <module>
    import initlization
  File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main (1)\BBDC-2BPracticalSlotAlertBot-main\initlization.py", line 6, in <module>
    import telegramBot
  File "C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main (1)\BBDC-2BPracticalSlotAlertBot-main\telegramBot.py", line 64, in <module>
    thread = threading.Thread(target=initlization.generateJSON())
AttributeError: partially initialized module 'initlization' has no attribute 'generateJSON' (most likely due to a circular import)

C:\Users\user\Desktop\BBDC-2BPracticalSlotAlertBot-main (1)\BBDC-2BPracticalSlotAlertBot-main>
```
I tested on a fresh install of windows 10 and I am unable to reproduce this error. What were the steps you took to get till this error?

**Comment by Nigel-Cheong** [comment]
update:
I manged to recreate this error by running telegramBot.py directly. Doing this will cause errors as such. 

Instead, only run start.py and not any of the other .py files 

let me know if you are still having issues. :)

**Comment by idevonic** [comment]
> update:
> I manged to recreate this error by running telegramBot.py directly. Doing this will cause errors as such.
> 
> Instead, only run start.py and not any of the other .py files
> 
> let me know if you are still having issues. :)

I see.
I tried using ubuntu, telegram seems to work. 
Only managed to show one slots available message and then got disconnected.
[Photo](https://ibb.co/NmsGJY0)

**Comment by Nigel-Cheong** [comment]
Please help clarify you meant by "disconnected". 

When connecting this application with your telegram bot, both bot ID and chat ID will be stored into credentials.json and will not change unless manually edited. The application will always be able to send you notification as it has your Bot ID and Chat ID to reference to. In turn, it will be connected.
As the application runs its check every time, if there are no available slots to notify the user of, it will not send any notification

**Comment by Nigel-Cheong** [comment]
Looking back at your previous comment, `However, there was no response from using /start from my bot.` and the photo you uploaded in the next comment, I would just like to add the telegram bot will not respond to any messages sent to it, including `/start`. `/start` is sent initially is to initialize the bot as well as to allow the python application to identify you.

Hope this clarifies the confusion regarding the bot responses from any messages sent to it
